blank_issues_enabled: false
contact_links:
  - name: Need help or have questions?
    url: https://google.com/
    about: If you're unsure how to proceed, reach out to us here.

issue_template:
  - name: Bug Report
    title: "ğŸ [Bug]: " 
    about: "Report a bug error in the code."
    labels: ["bug", "error"]